// src/App.tsx
import { useState } from "react";
import { Navigation } from "./components/Navigation";
import { Homepage } from "./components/Homepage";
import { OrderForm } from "./components/OrderForm";
import { Toaster } from "./components/ui/sonner";

export default function App() {
  const [currentPage, setCurrentPage] = useState<'home' | 'order'>('home');

  const navigateToOrder = () => setCurrentPage('order');

  return (
    <div className="min-h-screen bg-background">
      <Navigation 
        currentPage={currentPage} 
        onNavigate={setCurrentPage} 
      />
      
      {currentPage === 'home' ? (
        <Homepage onNavigateToOrder={navigateToOrder} />
      ) : (
        <OrderForm />
      )}
      
      <Toaster />
    </div>
  );
}

// src/App.vue
<template>
  <div class="min-h-screen bg-background">
    <Navigation 
      :current-page="currentPage" 
      @navigate="setCurrentPage" 
    />
    
    <Homepage 
      v-if="currentPage === 'home'"
      @navigate-to-order="navigateToOrder" 
    />
    <OrderForm v-else />
    
    <Toaster />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import Navigation from './components/Navigation.vue'
import Homepage from './components/Homepage.vue'
import OrderForm from './components/OrderForm.vue'
import Toaster from './components/ui/Toaster.vue'

type PageType = 'home' | 'order'

const currentPage = ref<PageType>('home')

const setCurrentPage = (page: PageType) => {
  currentPage.value = page
}

const navigateToOrder = () => {
  currentPage.value = 'order'
}
</script>
